### ISSUE TITLE
why the mbtiles map I made cna't display in example ?

### ISSUE THREAD

**Issue by WiFiInHand** [nutiteq/hellomap3d-ios#10]
I made a mbtiles format map. replace the filename and coord in offline map example. but the map can't display, do i miss something I should noticed?

**Comment by dproton** [comment]
https://drive.google.com/file/d/0B-b0zGcdks44NkF0Sl9DLWJTUW8/view?usp=sharing

I tested with this mbtiles, but it's not working. My code:

```
- (NTTileDataSource*)createTileDataSource
{
	// file-based local offline datasource
	NSString* fullpathVT = [[NSBundle mainBundle] pathForResource:@"hcmcity" ofType:@"mbtiles"];
	NTTileDataSource* vectorTileDataSource = [[NTMBTilesTileDataSource alloc] initWithMinZoom:0 maxZoom:5 path:fullpathVT];
	return vectorTileDataSource;
}

- (void)viewDidLoad
{
	[super viewDidLoad];
	
	// Get the base projection set in the base class
	NTProjection* proj = [[self.mapView getOptions] getBaseProjection];
	
	// Zoom to Rome
	[self.mapView setFocusPos:[proj fromWgs84:[[NTMapPos alloc] initWithX:106.660172 y: 10.762622]]  durationSeconds:0];
	[self.mapView setZoom:5 durationSeconds:0];
}
```

**Comment by jaakla** [comment]
From where did you get this .mbtiles file? This cannot be used in code as you describe, because it has a bit different format. If you want vector tile package from our service, then you have to use method described in https://developer.nutiteq.com/guides/offline-maps : _Download of bounding box_ - download the package to each device after first application start.

We don't provide currently mbtiles packages what you can bundle with apps. This is in the future plans through. Is this what you wish to get here?

**Comment by dproton** [comment]
Thank for your response ! 
I used your example in this repo (PackageManagerController example), download above package but I can't render it !

**Comment by jaakla** [comment]
The important part is following, you can not use NTMBTilesTileDataSource for our offline maps. 
```
// Create tile data source from PackageManager
NTTileDataSource* vectorTileDataSource = [[NTPackageManagerTileDataSource alloc] initWithPackageManager:_packageManager];

```
