### ISSUE TITLE
can't compile advancedmap3 project

### ISSUE THREAD

**Issue by Sh1mor1nka** [nutiteq/hellomap3d-ios#19]
Hello, i wan't yo see you SDK features but i can't compile project
![screen shot 2015-11-18 at 20 44 14](https://cloud.githubusercontent.com/assets/2759167/11250450/2b183924-8e35-11e5-819b-e4768b2f51da.png)

**Comment by mtehver** [comment]
What XCode version are you using? The current project contains libraries linked with XCode 7, so older XCode versions may not work.

**Comment by Sh1mor1nka** [comment]
I use XCode Version 7.1.1

**Comment by jaakla** [comment]
It seems that you have downloaded the project as zip file, not cloned it. The SDK is in git-lfs (as the binary is over 100MB github limit), so this download does not work. You should download Nuti.framework additionally from https://developer.nutiteq.com/downloads <https://developer.nutiteq.com/downloads> and replace one in hellomap3 folder. 

Or use proper git clone which does SDK download automatically from git-lfs

**Comment by Sh1mor1nka** [comment]
@jaakla you are right! Thank you!
But now i have a question. In Offline Vector Map Sample i can't find "Bermuda" location, i meah i find it but there are only ocean no land. This means that you don't have offline map for "Bermuda"?

**Comment by jaakla** [comment]
In packagemanager sample I can download Bermuda and it looks ok for me. 

Jaak

**Comment by Sh1mor1nka** [comment]
After download it appears, thank you!

**Comment by Sh1mor1nka** [comment]
@jaakla Sorry, but can i write in Objective-C not in Objective-C++?

**Comment by jaakla** [comment]
Yes, actually Nutiteq SDK has only Objective-C API, and not any public Objective-C++ API. Only thing is that internally it is C++ then you need to force project to compile with C++ also (by renaming a class from .m as .mm). Otherwise we have pure Objective-C API

However, please write your dev questions to stackoverflow or our dev group, not as issue comments here. This is not about some bug in this project. See the contacts here: https://developer.nutiteq.com/support <https://developer.nutiteq.com/support>

Jaak
